name: Debug Check Directory Existence

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Debug Check Directory Existence
      run: |
        ls /home/runner/work/OpenWrt-FastRhino-r68s-r66s/OpenWrt-FastRhino-r68s-r66s/openwrt/bin/targets/rockchip/armv8/
