name: Compile OpenWRT and Extract Kernel Version

on:
  push:
    branches:
      - main

jobs:
  build-and-extract-kernel-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        repository: 'openwrt/openwrt'

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python

    - name: Prepare .config file (Example)
      run: |
        # Configure for a specific target, e.g., rockchip r66s
        # This step will vary depending on your specific requirements
        make menuconfig

    - name: Compile OpenWRT
      run: |
        make -j$(nproc)

    - name: Extract Kernel Version
      run: |
        # Example of extracting the kernel version from a compiled image name
        # Adjust the path and filename pattern according to your build output
        cd bin/targets/rockchip/armv8/
        KERNEL_VERSION=$(echo $(ls *-squashfs-sysupgrade.img.gz) | sed -r 's/.*-([0-9]+\.[0-9]+)\..*/\1/')
        echo "KERNEL_VERSION=${KERNEL_VERSION}" >> $GITHUB_ENV

    - name: Print Kernel Version
      run: echo "Extracted Kernel Version is ${{ env.KERNEL_VERSION }}"
